Repository CubeArtisan/cubeartisan, pull requests merged in 2021-11, with the labels that each got.

#209 fix: Define dirname everywhere it is needed.
  server/routes/admin.js
  server/routes/misc.js
  server/routes/user.js
Labels: bug, backend, hotfix

#208 feat: Migrate to opentelemetry to reduce costs
  client/package.json
  server/__tests__/fixtures/examplecube.js
  server/__tests__/routes/cube/export.test.js
  server/package.json
  server/routes/index.js
  server/routes/middleware.js
  server/serverjs/winstonConfig.js
  yarn.lock
Labels: internal, backend, infrastructure, monitoring, dependencies

#210 fix: Lock the dockerfile node version since new versions are not comp…
  .docker/Dockerfile.jobs
Labels: bug, infrastructure, hotfix

#207 Fix/last pick dropped
  client/drafting/draftutil.js
  client/pages/CubeDraftPage.js
Labels: bug, frontend, drafting

#211 Draftlog import add default basics if missing
  server/routes/integrations.js
Labels: enhancement, backend

#213 Add additional debugging for the logging.
  server/serverjs/winstonConfig.js
Labels: bug, internal, infrastructure, monitoring

#215 Hotfix to get rid of ELK
  .docker/docker-compose.yml
  .github/workflows/actions.yml
  CONTRIBUTING.md
  README.md
  client/drafting/draftutil.js
  client/package.json
  client/pages/CubeDraftPage.js
  flake.lock
  server/.env_EXAMPLE
  server/__tests__/fixtures/examplecube.js
  server/__tests__/routes/cube/export.test.js
  server/package.json
  server/routes/card.js
  server/routes/deck.js
  server/routes/index.js
  server/routes/integrations.js
  server/routes/middleware.js
  server/serverjs/winstonConfig.js
  yarn.lock
Labels: infrastructure, monitoring, hotfix

#216 Patch v1.2.11
  server/routes/deck.js
Labels: bug, backend, hotfix
