Repository CubeArtisan/cubeartisan, pull requests merged in 2022-05, with the labels that each got.

#519 bug(ui): Catch errors when server side rendering.
  RELEASE_NOTES.md
  server/serverjs/render.js
Labels: bug, backend, hotfix

#534 feat(ui): Migrate the CubeAnalyticsPage to mui.
  .yarn/cache/@mui-private-theming-npm-5.7.0-473bdf8efc-197c318ad6.zip
  .yarn/cache/@mui-styled-engine-npm-5.7.0-fd6953863a-c9a5d21014.zip
  .yarn/cache/@mui-system-npm-5.7.0-6defc5ac15-7af90dd8ee.zip
  .yarn/cache/@mui-utils-npm-5.7.0-19a6d57b26-b2777938fb.zip
  .yarn/cache/@mui-x-data-grid-npm-5.10.0-fe36ebfed8-acc23999fe.zip
  .yarn/cache/@types-prop-types-npm-15.7.5-2aa48aa177-5b43b8b154.zip
  .yarn/cache/reselect-npm-4.1.5-bc046e41ae-54c13c1e79.zip
  client/components/AsfanDropdown.js
  client/components/HeaderCell.js
  client/components/LabeledSelect.js
  client/components/SortableTable.js
  client/components/analytics/AnalyticTable.js
  client/components/analytics/Averages.js
  client/components/analytics/Chart.js
  client/components/analytics/Cloud.js
  client/components/analytics/HyperGeom.js
  client/components/analytics/PivotTable.js
  client/components/analytics/PlaytestData.js
  client/components/analytics/Suggestions.js
  client/components/analytics/Tokens.js
  client/package.json
  client/pages/CubeAnalyticsPage.js
  loosely-type-checked-files.json
  typings/client/components/LabeledSelect.d.ts
  typings/client/components/LabeledSelect.d.ts.map
  typings/client/components/analytics/AnalyticTable.d.ts.map
  typings/client/components/analytics/Averages.d.ts.map
  typings/client/components/analytics/Chart.d.ts.map
  typings/client/components/analytics/HyperGeom.d.ts.map
  typings/client/components/analytics/PivotTable.d.ts.map
  typings/client/components/analytics/Suggestions.d.ts.map
  typings/client/components/analytics/Tokens.d.ts.map
  typings/client/pages/CubeAnalyticsPage.d.ts.map
  yarn.lock
Labels: enhancement, code-cleanup, frontend, ui

#539 bug(cube): Correctly recover the filter text for resizing.
  RELEASE_NOTES.md
  client/components/modals/ResizeModal.js
Labels: bug, frontend, hotfix

#546 Fix bugs
  client/components/ArticlePreview.js
  client/components/BlogPost.js
  client/components/CubePreview.js
  client/components/DraftbotBreakdown.js
  client/components/PaperHeader.js
  client/components/PodcastEpisodePreview.js
  client/components/PodcastPreview.js
  client/components/PreviewCard.js
  client/components/SiteAppBar.js
  client/components/SortableTable.js
  client/components/VideoPreview.js
  client/components/contexts/CubeContext.js
  client/components/layouts/MainLayout.js
  client/components/modals/LoginModal.js
  client/pages/CubeOverviewPage.js
  client/pages/DashboardPage.js
  client/pages/LandingPage.js
  client/theming/typography.js
  client/utils/Util.js
  loosely-type-checked-files.json
  server/routes/misc.js
  typings/client/components/ArticlePreview.d.ts.map
  typings/client/components/CubePreview.d.ts.map
  typings/client/components/DraftbotBreakdown.d.ts.map
  typings/client/components/PaperHeader.d.ts
  typings/client/components/PaperHeader.d.ts.map
  typings/client/components/PodcastEpisodePreview.d.ts.map
  typings/client/components/PodcastPreview.d.ts.map
  typings/client/components/PreviewCard.d.ts
  typings/client/components/PreviewCard.d.ts.map
  typings/client/components/SiteAppBar.d.ts.map
  typings/client/components/SortableTable.d.ts.map
  typings/client/components/VideoPreview.d.ts.map
  typings/client/components/contexts/CubeContext.d.ts
  typings/client/components/contexts/CubeContext.d.ts.map
  typings/client/components/layouts/MainLayout.d.ts.map
  typings/client/components/modals/LoginModal.d.ts.map
  typings/client/pages/DashboardPage.d.ts.map
  typings/client/pages/LandingPage.d.ts.map
  typings/client/utils/Util.d.ts.map
  typings/server/routes/misc.d.ts
  typings/server/routes/misc.d.ts.map
Labels: bug, enhancement, frontend, ui

#547 Port over more pages and components
  client/components/DeckPreview.js
  client/components/LabeledSelect.js
  client/components/SortableTable.js
  client/components/analytics/AnalyticTable.js
  client/components/analytics/Asfans.js
  client/components/layouts/CubeLayout.js
  client/pages/CubeAnalyticsPage.js
  client/pages/CubePlaytestPage.js
  client/theming/palettes/dark.js
  typings/client/components/DeckPreview.d.ts.map
  typings/client/components/LabeledSelect.d.ts
  typings/client/components/LabeledSelect.d.ts.map
  typings/client/components/SortableTable.d.ts
  typings/client/components/SortableTable.d.ts.map
  typings/client/components/analytics/AnalyticTable.d.ts.map
  typings/client/components/analytics/Asfans.d.ts
  typings/client/components/analytics/Asfans.d.ts.map
  typings/client/pages/CubeAnalyticsPage.d.ts.map
  typings/client/pages/CubePlaytestPage.d.ts.map
Labels: enhancement, code-cleanup, frontend, ui

#548 Merge prod
  RELEASE_NOTES.md
  client/components/DeckbuilderNavbar.js
  client/components/modals/ResizeModal.js
  client/utils/Card.js
  jobs/maintenance/clean_cubes.js
  jobs/package.json
  server/routes/misc.js
  server/routes/user.js
  server/scripts/force_update.js
  server/serverjs/render.js
  server/serverjs/updatecards.js
  typings/client/components/modals/ResizeModal.d.ts.map
  typings/client/utils/Card.d.ts.map
  typings/server/routes/user.d.ts.map
  typings/server/serverjs/render.d.ts.map
  typings/server/serverjs/updatecards.d.ts.map
Labels: internal

#553 feat(ui): Implement several suggested UI updates from feedback.
  client/components/CubeListNavbar.js
  client/components/CubeNavbar.js
  client/components/LabeledSelect.js
  client/components/SiteAppBar.js
  client/components/StyledButtonMenu.js
  client/components/layouts/MainLayout.js
  client/pages/CubePlaytestPage.js
  client/theming/base.js
  client/theming/palettes/dark.js
  client/theming/palettes/light.js
  typings/client/components/CubeListNavbar.d.ts.map
  typings/client/components/CubeNavbar.d.ts.map
  typings/client/components/StyledButtonMenu.d.ts
  typings/client/components/StyledButtonMenu.d.ts.map
  typings/client/components/layouts/MainLayout.d.ts.map
  typings/client/pages/CubePlaytestPage.d.ts.map
  typings/client/theming/base.d.ts
  typings/client/theming/base.d.ts.map
  typings/client/theming/palettes/dark.d.ts
Labels: enhancement, code-cleanup, frontend, ui

#573 Override Name Import
  server/serverjs/cubefn.js
  typings/server/serverjs/cubefn.d.ts
  typings/server/serverjs/cubefn.d.ts.map
Labels: enhancement, backend

#576 feat(ui): Add the name as a title to the token cards.
  client/components/analytics/Tokens.js
Labels: enhancement, frontend, ui
